# TiDB Cloud MySQL Database Configuration
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3
spring.datasource.username=33N8Zn2zmtSCuQh.root
spring.datasource.password=vQp7Sf4NqrY5S4Ri
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=${PORT:3000}

# JWT Configuration
app.jwt.secret=wH5Gv6ehSPXFgBs2aoFtPV8/yIlChDlQxqf5Q0h/c1BsGjE0SD4Lp/ScsMm8TLwrTthagSaekaFq3L86cPLaFw==
