spring:
  profiles:
    active: mysql
  application:
    name: feedback-workflow
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY&enabledTLSProtocols=TLSv1.2,TLSv1.3}
    username: ${DATABASE_USERNAME:33N8Zn2zmtSCuQh.root}
    password: ${DATABASE_PASSWORD:vQp7Sf4NqrY5S4Ri}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: ${PORT:3000}

app:
  jwt:
    secret: ${JWT_SECRET:wH5Gv6ehSPXFgBs2aoFtPV8/yIlChDlQxqf5Q0h/c1BsGjE0SD4Lp/ScsMm8TLwrTthagSaekaFq3L86cPLaFw==}



